#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#les route CRUD dossier
# Routes pour l'entité Dossier

api_dossier_list:
  path: /api/dossiers
  methods: GET
  controller: App\Controller\DossierController::listDossiers

api_dossier_get:
  path: /api/dossiers/{id}
  methods: GET
  controller: App\Controller\DossierController::getDossier

api_dossier_create:
  path: /api/dossiers
  methods: POST
  controller: App\Controller\DossierController::createDossier

api_dossier_update:
  path: /api/dossiers/{id}
  methods: PUT
  controller: App\Controller\DossierController::updateDossier

api_dossier_delete:
  path: /api/dossiers/{id}
  methods: DELETE
  controller: App\Controller\DossierController::deleteDossier

