#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# Routes pour l'entité Dossier CRUD dossier

api_dossier_list:
  path: /api/dossiers
  methods: GET
  controller: App\Controller\DossierController::listDossiers

api_dossier_get:
  path: /api/dossiers/{id}
  methods: GET
  controller: App\Controller\DossierController::getDossier

api_dossier_create:
  path: /api/dossiers
  methods: POST
  controller: App\Controller\DossierController::createDossier

api_dossier_update:
  path: /api/dossiers/{id}
  methods: PUT
  controller: App\Controller\DossierController::updateDossier

api_dossier_delete:
  path: /api/dossiers/{id}
  methods: DELETE
  controller: App\Controller\DossierController::deleteDossier

# Routes pour l'entité Prime CRUD prime

api_prime_list:
  path: /api/primes
  methods: GET
  controller: App\Controller\PrimeController::listPrimes

api_prime_get:
  path: /api/primes/{id}
  methods: GET
  controller: App\Controller\PrimeController::getPrime

api_prime_create:
  path: /api/primes
  methods: POST
  controller: App\Controller\PrimeController::createPrime

api_prime_update:
  path: /api/primes/{id}
  methods: PUT
  controller: App\Controller\PrimeController::updatePrime

api_prime_delete:
  path: /api/primes/{id}
  methods: DELETE
  controller: App\Controller\PrimeController::deletePrime
