#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# Routes pour l'entité Dossier CRUD dossier

api_dossier_list:
  path: /api/dossiers
  methods: GET
  controller: App\Controller\DossierController::listDossiers

api_dossier_get:
  path: /api/dossiers/{id}
  methods: GET
  controller: App\Controller\DossierController::getDossier

api_dossier_create:
  path: /api/dossiers
  methods: POST
  controller: App\Controller\DossierController::createDossier

api_dossier_update:
  path: /api/dossiers/{id}
  methods: PUT
  controller: App\Controller\DossierController::updateDossier

api_dossier_delete:
  path: /api/dossiers/{id}
  methods: DELETE
  controller: App\Controller\DossierController::deleteDossier

# Routes pour l'entité Prime CRUD prime

api_prime_list:
  path: /api/primes
  methods: GET
  controller: App\Controller\PrimeController::listPrimes

api_prime_get:
  path: /api/primes/{id}
  methods: GET
  controller: App\Controller\PrimeController::getPrime

api_prime_create:
  path: /api/primes
  methods: POST
  controller: App\Controller\PrimeController::createPrime

api_prime_update:
  path: /api/primes/{id}
  methods: PUT
  controller: App\Controller\PrimeController::updatePrime

api_prime_delete:
  path: /api/primes/{id}
  methods: DELETE
  controller: App\Controller\PrimeController::deletePrime


  # Routes pour l'entité Salarie CRUD salarie

api_salarie_create:
  path: /api/salaries
  methods: POST
  controller: App\Controller\SalarieController::createSalarie

api_salarie_list:
  path: /api/salaries
  methods: GET
  controller: App\Controller\SalarieController::listSalaries

api_salarie_get:
  path: /api/salaries/{id}
  methods: GET
  controller: App\Controller\SalarieController::getSalarie

api_salarie_prime_get:
  path: /api/salaries/{id}/prime
  methods: GET
  controller: App\Controller\SalarieController::getprimesalarie


api_salarie_update:
  path: /api/salaries/{id}
  methods: PUT
  controller: App\Controller\SalarieController::updateSalarie

api_salarie_delete:
  path: /api/salaries/{id}
  methods: DELETE
  controller: App\Controller\SalarieController::deleteSalarie

